[build]
  command = "npm run build"
  functions = "dist"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[env.production]
  NODE_ENV = "production"
